const appname = "ZarafyStore";
const appversion = "Version 1.0.0";
const credits = "@santi_boop";
const name = "Name";
const nameHint = "Enter your name";
const emailHint = "admin@mail.com";
const passwordHint = "**********";
const password = "Password";
const email = "Email";
const retypePassword = "Retype Password";
const retypeName = "Retype Name";
const forgotPassword = "Forgot Password?";
const login = "Login";
const signUp = "Sign Up";
const createAccount = "Create Account";
const loginWith = "Login with";
const privacyPolicy = "Privacy Policy";
const termsAndConditions = "Terms and Conditions";
const AlreadyHaveAnAccount = "Already have an account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    profile = "Profile",
    settings = "Settings",
    logout = "Logout";
const searchanything = "Search anything",
    todayDeals = "Today Deals",
    flashSale = "Flash Sale",
    topBrands = "Top Brands",
    womenDress = "Women dressed",
    girlsWatches = "Girls Watcher",
    mobiles = "Mobiles",
    boysGlasses = "glasses",
    tShirts = "Tshirts",
    girlsDressed = "Girls dress",
    featuredProducts = "Featured Products",
    topSeller = "Top Seller",
    brands = "Brands",
    topCategories = "Top Categories",
    featuredCategories = "Featured Categories",
    newArrivals = "New Arrivals",
    popularProducts = "Popular Products",
    seeAll = "See All",
    seeMore = "See More",
    seeLess = "See Less",
    addToCart = "Add to Cart",
    buyNow = "Buy Now",
    productDetails = "Product Details",
    productDescription = "Product Description",
    productReviews = "Product Reviews",
    product = "Product",
    description = "Description",
    reviews = "Reviews",
    relatedProducts = "Related Products",
    price = "Price",
    quantity = "Quantity",
    total = "Total",
    checkout = "Checkout",
    payment = "Payment",
    orderSummary = "Order Summary",
    orderDetails = "Order Details",
    order = "Order",
    orderDate = "Order Date",
    orderStatus = "Order Status",
    orderTotal = "Order Total",
    orderItems = "Order Items",
    orderID = "Order ID",
    orderDelivered = "Order Delivered",
    orderPending = "Order Pending",
    orderCancelled = "Order Cancelled",
    orderProcessing = "Order Processing",
    orderShipped = "Order Shipped",
    orderOnTheWay = "Order On The Way",
    orderReceived = "Order Received";

const womenClothing = "Women Clothing",
    menClothing = "Men Clothing and Accessories",
    automobile = "Automobile and Motorcycles",
    computer = "Computer and Office",
    kidtoys = "Kid Toys",
    sports = "Sports and Outdoor",
    jewelery = "Jewelery and Watches",
    cellphones = "Cellphones and Accessories",
    furniture = "Home and Furniture";

const video = "Video",
    sellerpolicy = "Seller Policy",
    returnPolicy = "returnpolity ",
    supportPolicy = "Support Policy",
    productosyoumaylike = "Products you may like",
    about = "About";

const wishList = "My wishlist", myOrders = "My Orders", messages = "My messages", shippingAddress = "Shipping Address", settingsAccount = "Settings Account", settingsNotification = "Settings Notification", settingsSecurity = "Settings Security", settingsLanguage = "Settings Language", settingsCurrency = "Settings Currency", settingsDarkMode = "Settings Dark Mode", settingsHelp = "Settings Help", settingsAbout = "Settings About", settingsLogout = "Settings Logout";
